language: node_js
cache: npm

install:
	npm install --save apollo-boost react-apollo graphql
	npm add graphql-request graphql
	npm install --save @apollo/client graphql
	npm install --save @material-ui/core
	npm install --save @material-ui/icons
	npm install --save moment react-moment
	npm ci
deploy:
	provider: pages
	skip-cleanup: true
	github-token: $GitHub_Token
	local_dir: build
	on:
		branch:master
